### ISSUE TITLE
I have a very important question to ask you about the cnn-number-detection, time-urgent,Chinese student, can you give a contact way?

### ISSUE THREAD

**Issue by guojianyang** [FabianGroeger96/cnn-number-detection#13]

**Comment by FabianGroeger96** [comment]
Hi there, you can ask it here. What is your important question?

**Comment by guojianyang** [comment]
Hello, my question is why I will be prompted to need X.pickle and y.pickle when running the test_model.py script if I use the weight file you provide CNN-gnet-deep-v2-ultimate.h5 for prediction? Don't they use it in training? Do I also need these two files when testing?




| |
郭建洋
|
|
***@***.***
|

签名由 网易邮箱大师 定制

On 04/11/2021 17:49, Fabian Gröger wrote:

Hi there, you can ask it here. What is your important question?

**Comment by FabianGroeger96** [comment]
No, this should not be the case. I fixed it in the commit 60fc19ae1e1e1249e450f52577771a469887493b.

**Comment by guojianyang** [comment]
Thanks,I 'll try it again




| |
郭建洋
|
|
***@***.***
|

签名由 网易邮箱大师 定制

On 04/13/2021 20:23, Fabian Gröger wrote:

Closed #13.
