### ISSUE TITLE
Line 132 in isolator.py

### ISSUE THREAD

**Issue by kkalenbe** [FabianGroeger96/cnn-number-detection#14]
Hello Fabian,

I think there is a bug in lien 132 of isolator.py

```_, contours, hierarchy = cv2.findContours(image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)```

which results in ```ValueError: not enough values to unpack (expected 3, got 2)```

should be 

```contours, hierarchy = cv2.findContours(image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)```

**Comment by FabianGroeger96** [comment]
Thanks for spotting. The return values changed since OpenCV version 3.2, and I never updated it :smile: 
Fixed in commit (636434c0f7660ecccbbd5adca5bbb316ba629507).
