### ISSUE TITLE
Pip3 requirements

### ISSUE THREAD

**Issue by mshvarts** [FabianGroeger96/cnn-number-detection#5]
Sorry if this is a noob question, but i encounter this error when running the command "pip3 install -r requirements.txt"? 
 

ERROR: Could not find a version that satisfies the requirement tensorflow>=1.4.1 (from -r requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for tensorflow>=1.4.1 (from -r requirements.txt (line 7))

Im using windows 64 , Python 3.5.2 , and pip 19.3.1 . Thanks

**Comment by mshvarts** [comment]
Oh i think i need python 64 bit for this...

**Comment by mshvarts** [comment]
Nvm that didn't seem to help.. i tried python 3.7.3 as well

**Comment by mshvarts** [comment]
Ok so im using AMD gpu.. could that be the issue?

**Comment by crzdg** [comment]
May this stackoverflow posts helps you out

https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip

Just try to search for a wheel-File for the desired tensorflow version. Also consult the tensorflow documentation for more informations. 

Also note we used Python 3.6 in this project.

**Comment by mshvarts** [comment]
I see.. but that answer link he posted looks like its for mac? will it work on windows?
I will try it anyway. Thanks

**Comment by FabianGroeger96** [comment]
Did it work? Or do you still have the same issue?

**Comment by ugotjelly** [comment]
I dont know, i dont really understand how to run it.. 

>python extract_data.py
Traceback (most recent call last):
  File "extract_data.py", line 1, in <module>
    from DataExtractor.extractor import Extractor
ImportError: No module named 'DataExtractor'

**Comment by ugotjelly** [comment]
Ok i did pip install natsort and pipinstall tqdm now i get this error ...

>Traceback (most recent call last):
  File "DataExtractor/extract_data.py", line 1, in <module>
    from DataExtractor.extractor import Extractor
  File "C:\...\cnn-number-detection\DataExtractor\extractor.py", line 11, in <module>
    from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
ImportError: No module named 'tensorflow'

I dont really have time to figure this out now i have to study other things tomorrow

**Comment by mshvarts** [comment]
No.. still trying to get it to work. Turns out i was using pip from another python directory. lol But after i deleted all other python versions and reinstalled packages using the right pip i get this error now

 python DataExtractor/extract_data.py
>Using TensorFlow backend.
C:\Python36\lib\site-packages\skimage\external\tifffile\tifffile.py:305: UserWarning: ImportError: No module named '_tifffile'. Loading of some compressed images will be very slow. Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "ImportError: No module named '_tifffile'. "
Traceback (most recent call last):
  File "DataExtractor/extract_data.py", line 2, in <module>
    from Trainer.Models.model_gnet_deep_v2 import ModelGNetDeepV2

**Comment by mshvarts** [comment]
@FabianGroeger96  Broo @crzdg  do you guys have any ideas?? Did you guys even test this on clean 
 python windows 10 installation? Do i need linux or some missing python libraries to make this work?

**Comment by crzdg** [comment]
@ugotjelly Hi!

We do not have time to solve this problem at the moment as we in big stress with work at the end of the year.

For sure this is tested and working? Tested against Mac, Linux (Raspberry Pi) and Windows. I'm happy to test it again as soon I can get into it.

Meanwhile, please watch your tone! We normally don't give any support for problems which clearly environment related. We assume that you have the proper knowledge and background to get projects like this running. We're doing this out of goodwill!

Please study the README again and follow the steps carefully and completly. This project won't run out of the box, as clearly stated in the README.

Enjoy your weekend. I will get back to you as soon wee find time for it.

**Comment by mshvarts** [comment]
Ok thanks

**Comment by mshvarts** [comment]
python DataExtractor/extract_data.py
Traceback (most recent call last):
  File "DataExtractor/extract_data.py", line 1, in <module>
    from DataExtractor.extractor import Extractor
  File "C:\Users\user\Desktop\CnnOCR\cnn-number-detection\DataExtractor\extractor.py", line 11, in <module>
    from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by FabianGroeger96** [comment]
@ugotjelly 
We will do a refactoring of our code so that it is easier to use. We will keep you updated.
Thank you for your remarks
