### ISSUE TITLE
Not clear what format the date should be given in order to train it

### ISSUE THREAD

**Issue by alexmoruz** [FabianGroeger96/cnn-number-detection#7]
Hello,
Was trying to run it on my local machine but unfortunately got stuck at the stage of what format data it requires to be provided and how it should be labelled.

It would be great if you could add some samples of data which it requires so it clear how to feed the data into it :)

Best regards,
Alex

**Comment by crzdg** [comment]
Hi!

Sorry for the delayed answer. We're quite busy.
However, which data do you mean? For the model or the whole pipeline. The data pipeline look something like this.


1. Raspi Image in any res (we used 320x24) 
2. Isolator isolates regions of interests (ROI). Regions which potentially are a number get cropped to 28x28 (not 100% sure, but as I remember)
3. The ROI gets classified by the network either to a number or to the noise category.

Let me know if you want to know more. I also could spare some time to help over voice chat, starting next week.
